My_Second_Project/My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login_app.urls')),
]

My_Second_Project/login_app/urls.py
from django.conf.urls import url
from django.urls import path
from login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = 'login_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name = 'login'),
    path('user_login/',views.user_login, name = 'user_login'),
    path('logout/',views.user_logout, name = 'logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

My_Second_Project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


# username, password, email

# Extra info we need from user
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    facebook_id = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)
    def __str__(self):
        return self.user.username

My_Second_Project/login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'password', 'email')

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

My_Second_Project/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm, UserInfoForm
from django.contrib.auth.models import User
from login_app.models import UserInfo

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.

def login_page(request):
    diction = {}
    return render(request, 'login_app/login.html', context = diction)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('login_app:index'))

                # below techinque doesn't show url pattern
                # return render(request, 'login_app/index.html', context={})
                # return index(request)
            else:
                return HttpResponse("<div class='alert alert-danger'>Account is not Active!!</div>")
        else:
            return HttpResponse("<div class='alert alert-danger'>Login details are Wrong!</div>")
    else:
        return HttpResponseRedirect(reverse('login_app:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_app:index'))

def index(request):
    diction = {}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        diction = {'user_basic_info':user_basic_info, 'user_more_info':user_more_info}
    return render(request, 'login_app/index.html', context=diction)


def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()
            registered = True
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    diction = {'user_form': user_form, 'user_info_form': user_info_form, 'registered':registered}
    return render(request, 'login_app/register.html', context=diction)

My_Second_Project/templates/login_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{{title}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'login_app:index' %}">Home</a>
        {% if user.is_authenticated %}
        <a class="nav-link"  href="{% url 'login_app:logout' %}">Logout</a>
        {% else %}
        <a class="nav-link"  href="{% url 'login_app:register' %}">Register</a>
        <a class="nav-link"  href="{% url 'login_app:login' %}">Login</a>
        {% endif%}
      </div>
    </div>
  </div>
</nav>
<div class = 'container' style = "padding-top:20px">
  {% block body_block%}

  {% endblock%}
</div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

My_Second_Project/templates/login_app/index.html
{% extends 'login_app/base.html' %}
{% block body_block %}
{% if user.is_authenticated %}
<p> Hi {{user_basic_info.username}}</p>
<p>Your Email is {{user_basic_info.email}}</p>
<p><a href="{{user_more_info.facebook_id}}" target="_bl
  ">Facebook Profile</a></p>
<img src="/media/{{user_more_info.profile_pic}}" width="200px" alt='rizbi20'>
{% else %}
<div class = "alert alert-danger">You are not authenticated!!</div>
{% endif %}
{%endblock%}

My_Second_Project/templates/login_app/login.html
{% extends 'login_app/base.html' %}
{% block body_block %}
<h3> Please Login</h3>
<form action="{%url 'login_app:user_login' %}" method="post">
  <label for = 'username'>Username:</label>
  <input type="text" name="username" placeholder="Enter Username" required class = "form-control">
  <label for = 'password'>Password:</label>
  <input type="password" name="password" placeholder="Enter Password" required class = "form-control">
  {% csrf_token %}
  <input type="submit" name = "submit" value = "Login" class = "btn btn-success btn-sm" >
</form>
{% endblock %}

My_Second_Project/templates/login_app/register.html
{% extends 'login_app/base.html' %}
{% load static %}
{% block body_block %}
{% if registered%}
<div class = "alert alert-success"> Congratulations! Registration Successfull!!</div>
{% else %}
<form enctype="multipart/form-data" method="POST">
  {{ user_form.as_p }}
  {{ user_info_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Register" class='btn btn-info btn-sm'>
</form>
{% endif %}
{%endblock%}